# Generated by Django 3.0.5 on 2020-04-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='listings.State'),
            preserve_default=False,
        ),
    ]
